### PR TITLE
adding string length calculation 

### PR DESCRIPTION
**Pull request by kanitw**
Max length is useful for visualization layout.  

I want to eliminate vl.data.getStats from vegalite and only use `dl.profile` instead.

### CODE REVIEW

**Comment by jheer** [comment]
I'm not sure why you are making these changes. Profile already computes string length statistics if the input data is string-typed (read the code!). You also changed the variance calculation in a way that will give different results.

**Comment by kanitw** [comment]
Profile already computes string length statistics if the input data is string-typed 

That’s not true.   Profile calculates min, max in in terms of sort order.  

The old `dl.profile(['aa','bb','aaaaaaa’])` returns 
``
{
  max: “bb”,
  min: “aa”,
  ...
}
```
My code augment this with `profile_result.length = {min:2 max:7}`



Regarding variance calculation, sorry about that -- i've just reverted the change.

**Comment by jheer** [comment]
Ah yes. Let's simply move the min/max updates to *after* the string length
transform. This will also make the output of profile consistent with the
new groupby aggregation facilities I'm working on.

**Comment by kanitw** [comment]
That's good too    

```
{
  max: “bb”,
  min: “aa”,
  ...
}
```

isn't particularly useful anyway.    To avoid conflict, do you want me to do it or do you want to do it yourself?

**Comment by jheer** [comment]
Go ahead and make a PR. I'm busy working on a separate branch right now.

**Comment by kanitw** [comment]
I’ve just pushed new PR (#11).

**Pull request closed without merging**
