### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by kanitw**
- Added bower.json and register `datalib` in bower’s directory.  Now people can also install datalib with bower.   (`bower install datalib`)

### CODE REVIEW

**Comment by kanitw** [comment]
@jheer    I was reading more about bower and 
it seems like it requires us to put the compiled file in the repo, otherwise people won't be able to use it right away after running `bower install datalib`.

**Comment by domoritz** [comment]
Maybe deploy to `gh-pages` with a simple shell script like https://github.com/uwdata/vegalite/blob/master/deploy.sh.

**Comment by kanitw** [comment]
The thing is bower track versions by semver it tag.  If we push publish only the latest version to gh-pages, it doesn't help bower track versions.  Unless we tag gh-pages branch instead, which i think is even worse!



—
Kanit "Ham" Wongsuphasawat
http://kanitw.yellowpigz.com/ 


Painfully tapped iPhone keyboard--only for you.  Sorry for brevity and typos.

**Comment by kanitw** [comment]
Okay.  Now I know the solution.  We can include distributed files only in the releases.  

See chafnan’s comment in https://github.com/knockout/knockout/issues/1039.

**Pull request merged**
